language: java
install: mvn install -Dtest=\!DBUtilsTest* -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V
jdk:
  - oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)
